name: Executing Tests

-uses:-ssettings-xml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    needs: docker_build
    runs-on: ubuntu-latest
    container:
      image: ubandc2/chethana:main-6c58979
    steps: 
    - name: execute test
      run: |
           env
           cd /usr/src/app
           ls
           mvn clean install -s settings.xml
           mvn clean test -P PROD -s settings.xml "-Dsurefire.suiteXmlFiles=pipeDriveDealVerificationSuite.xml"
      env:
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
         
#   test:
        
#    runs-on: windows-latest

#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: '1.8'
#        distribution: 'temurin'
#        cache: maven
        
#    - name: Run with Maven
#      run: mvn clean test -P PROD "-Dsurefire.suiteXmlFiles=pipeDriveDealVerificationSuite.xml"
#      env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
#    needs: build
